export { default as Dots } from "./Dots";
export { default as Camera } from "./Camera";
export { default as Mic } from "./Mic";
export { default as Pen } from "./Pen";
export { default as PhoneCall } from "./PhoneCall";
export { default as UserPlus } from "./UserPlus";
export { default as VolumnOff } from "./VolumnOff";
export { default as Zoom } from "./Zoom";
export { default as Logout } from "./Logout";
